name: Prettier linting

on:
  pull_request:
  pull_request_target:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: creyD/prettier_action@v4.3
        with:
          # Fail if differences are found
          prettier_options: --list-different **/*.{js,ts}
